export enum ActionsEnum {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  READ_USER = 'READ_USER',
  CREATE_ACTION = 'CREATE_ACTION',
  UPDATE_ACTION = 'UPDATE_ACTION',
  DELETE_ACTION = 'DELETE_ACTION',
  READ_ACTION = 'READ_ACTION',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  READ_ROLE = 'READ_ROLE',
}
